version: "3.7"
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    container_name: zk
  kafka:
    image: 'bitnami/kafka:2.8.1'
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zk:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    container_name: kafka
  spark-python:
    image: jupyter/all-spark-notebook:spark-3.1.2
    ports:
      - "8888:8888"
      - "4040-4080:4040-4080"
    links:
      - "kafka:kafka-server"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks/
    container_name: spark-python

  flink-job-manager:
    image: pyflink/playgrounds:1.13.0-rc2
    hostname: "jobmanager"
    ports:
      - "6123:6123"
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    container_name: flink-job-manager

  flink-task-manager:
    image: pyflink/playgrounds:1.13.0-rc2
    ports:
      - "6121:6121"
      - "6122:6122"
    depends_on:
      - flink-job-manager
    command: taskmanager
    links:
      - flink-job-manager:jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=20
    container_name: flink-task-manager

  zeppelin:
    image: apache/zeppelin:0.10.0
    ports:
      - "7077:7077"
      - "8080:8080"
    depends_on:
      - flink-task-manager  
    volumes:
      - ./notebooks:/notebook
      - ./logs:/logs
    environment:
      ZEPPELIN_NOTEBOOK_DIR: /notebook
      ZEPPELIN_LOG_DIR: /logs
    container_name: zeppelin  
